# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
dist: trusty

before_install:
  - sudo apt-get install libmagick++-dev

env:
  global:
     - R_CHECK_ARGS="--no-build-vignettes --no-manual"
